### PR TITLE
Py3 fixes

### PR DESCRIPTION
**Pull request by jmrohwer**
Hi Carl,

I have finished the port to Python 3 and updated all the documentation and example notebooks to reflect this as well. The documentation is also slightly extended and fixed in parts. The documentation builds with Sphinx on my machine, but I have not tested on readthedocs as I don't have access.

I'd appreciate it if you could:
- briefly check the PR
- merge if you are happy
- grant me access to the readthedocs project using my github name. I'll then double check that the docs build fine on readthedocs as well.

Thanks,
Johann

### CODE REVIEW

**Comment by exe0cdc** [comment]
Hi Johann,

I have gone over the code and everything looks good. I have given you access to readthedocs, let me know if you have any issues. I see you are still adding stuff to the PR so I will merge later tonight.

**Comment by jmrohwer** [comment]
Thanks, I thought it would be nice to distribute a PDF of the docs in the build as well so users have immediate access to the documentation after installing, also as reference without having to go online. I'll add a note on the README as well.

I'll give you a heads up when I'm done with all commits to this branch. Thanks for looking at it so long.

**Comment by jmrohwer** [comment]
Hi Carl, should be good to go now. The documentation builds with RTD.

**Comment by exe0cdc** [comment]
Hi Johann,

Thanks. I'm merging now.

**Pull request merged**
